blank_issues_enabled: false
contact_links:
  - name: Question (via Telegram groups)
    url: https://github.com/IATNAOD/tgify#resources
    about: Ask and answer questions about tgify
  - name: Question (via GitHub Discussions)
    url: https://github.com/IATNAOD/tgify/discussions/categories/q-a
    about: Ask and answer questions about tgify
